<script>
import { percentText } from '../utils/exactDecimal'
// 金额仅展示服务端 Decimal 字符串，禁止浏览器重新计算或转换 Number。
export default { name: 'BusinessResult', props: { result: { type: Object, required: true } }, data() { return { groupPage: 1 } }, watch: { result() { this.groupPage = 1 } }, computed: { groupRows() { return (this.result.groups || []).slice((this.groupPage - 1) * 100, this.groupPage * 100) } }, methods: { label(key) { return ({ revenue: '收入', gmv: '成交额', quantity: '销量', cost: '成本', profit: '利润', operating_expense: '运营费用', budget: '预算', actual: '实际金额', records_count: '记录数', order: '订单数', customer: '客户数', gross_profit: '毛利润', gross_margin: '毛利率', operating_profit: '简化经营利润', operating_margin: '经营利润率', profit_margin: '利润率', variance: '预算差额', variance_rate: '预算差异率' })[key] || key }, value(item) { return item?.value ?? item?.explanation ?? '未定义'; }, percent(item) { return percentText(item?.value) ?? item?.explanation ?? '未定义' }, share(value) { return percentText(value) ?? '总变化为零，贡献未定义' }, range(item) { return item ? `${item.start} 至 ${item.end}（观测 ${item.observed_periods} / 预期 ${item.expected_periods} 期）` : '未提供区间' } } }
</script>
<template><section class="phase3-workbench" aria-label="业务指标结果">
 <h3>业务指标</h3><p>数据版本 {{ result.dataset_version ?? '未记录' }} · {{ result.currency || '币种未确认' }} · {{ result.unit || '单位未确认' }}</p>
 <table v-if="result.kind === 'kpi'" class="data-table"><thead><tr><th>指标</th><th>结果</th></tr></thead><tbody><tr v-for="(item, key) in result.metrics" :key="key"><th>{{ label(key) }}</th><td>{{ key.endsWith('margin') || key.endsWith('rate') ? percent(item) : value(item) }}</td></tr></tbody></table>
 <template v-else><p>本期：{{ range(result.current_range) }}</p><p>对比期：{{ range(result.previous_range) }}</p><dl><dt>本期值</dt><dd>{{ value(result.current) }}</dd><dt>对比期值</dt><dd>{{ value(result.previous) }}</dd><dt>绝对变化</dt><dd>{{ value(result.delta) }}</dd><dt>百分比变化</dt><dd>{{ percent(result.growth_rate) }}</dd></dl></template>
 <div v-if="result.groups?.length" class="table-wrap phase3-table"><table class="data-table"><thead><tr><th>{{ result.dimension }}</th><th>本期</th><th>对比期</th><th>变化</th><th>贡献比例</th></tr></thead><tbody><tr v-for="(row, index) in groupRows" :key="index"><td>{{ row.dimension ?? '缺失维度' }}</td><td>{{ row.current }}</td><td>{{ row.previous }}</td><td>{{ row.delta }}</td><td>{{ share(row.contribution_share) }}</td></tr></tbody></table><p>共 {{ result.groups.length }} 个分组，当前第 {{ groupPage }} 页，每页最多100个。</p><el-button :disabled="groupPage === 1" @click="groupPage--">上一页分组</el-button><el-button :disabled="groupPage * 100 >= result.groups.length" @click="groupPage++">下一页分组</el-button></div>
 <p v-for="note in result.limitations" :key="note" class="summary-warning">{{ note }}</p><p class="caption">结果来源：{{ result.source_ref }}</p>
</section></template>
